version: '2'

services:
  db:
    build:
      context: ./db
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
  web:
    build:
      context: ./web
    container_name: web
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=ratestask
    ports:
      - "80:80"
